# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 45e92ba6d63ea1dd21e621dbb10acb664d847b826409ee862fc71b910ba0b4817f0f0ab601a7063a8832ab25a14dd9c2aa93236e5c93d5065d705720172970ab

test:
  secret_key_base: 7237dfe157a491f682ff999e67e83a0e33e21b98e1e1727b6ef39b1d8a0c9b3847d0efb249ac88a548dd2aa10afcde9bc458e0905077e26aca17292155c43dd0

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
